[tool.black]
target_version = ['py313']
# Keep exclude in sync with flake8 config in tox.ini
exclude = '''
/(
      \.git
    | \.tox
    | node_modules
    | __pycache__
    | \*\.pyc
    | \.eggs
    | .*\.egg
    | .*\.egg-info
    | env
    | venv
    | .*venv.*
    | \.serverless
)/
'''
