frameworkVersion: ">=1.50.0 <2.0.0"

service: data-uploader

provider:
  name: aws
  runtime: python3.7
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ok-origo-dataplatform-config-${self:provider.stage}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  environment:
    GIT_REV: ${git:branch}:${git:sha1}
  iamManagedPolicies:
    - Fn::Join:
        - ":"
        - - "arn:aws:iam:"
          - Ref: "AWS::AccountId"
          - "policy/data-uploader-policy"
  tags:
    GIT_REV: ${git:branch}:${git:sha1}

plugins:
  - serverless-aws-documentation
  - serverless-python-requirements
  - serverless-plugin-git-variables

resources:
  Description: >
    ${self:service} ${git:branch}:${git:sha1}

    ${git:message}

package:
  exclude:
    - "**/*"
  include:
    - uploader/*.py
    - doc/models/*.json

functions:
  generate_signed_post:
    handler: uploader.generate_signed_post.handler
    environment:
      BUCKET: "ok-origo-dataplatform-${self:provider.stage}"
      METADATA_API: ${ssm:/dataplatform/metadata-api/url}
      AUTHORIZER_API: { Fn::ImportValue: AuthorizerApiUrl }
    layers:
      - { Fn::ImportValue: PythonBaseLambdaLayer }
    events:
      - http:
          path: /
          method: post
          cors: true
          authorizer:
            arn: arn:aws:lambda:${self:provider.region}:***REMOVED***:function:keycloak-authorizer-${self:provider.stage}-authenticate
            resultTtlInSeconds: 300
            identitySource: method.request.header.Authorization
            identityValidationExpression: "^Bearer [-0-9a-zA-Z\\._]*$"
            type: token
          documentation:
            summary: Generate a signed POST URL
            description: Generates a signed POST URL that a new distribution can be uploaded to
            requestModels:
              "application/json": UploadRequest
            methodResponses:
              - statusCode: "200"
                responseModels:
                  "application/json": UploadResponse
              - statusCode: "400"
                responseModels:
                  "application/json": ErrorResponse
              - statusCode: "403"
                responseModels:
                  "application/json": ErrorResponse
              - statusCode: "500"
                responseModels:
                  "application/json": ErrorResponse
custom:
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    usePoetry: false
  documentation:
    info:
      title: Data Uploader
      version: 0.0.1
      summary: Data Uploader API
      description: Creates a signed URL and parameters that can be used to POST a file to the S3 upload bucket.
    models:
      - name: UploadRequest
        description: Request to upload a file to S3
        contentType: "application/json"
        schema: ${file(doc/models/uploadRequest.json)}
      - name: UploadResponse
        description: Response object with the presigned post url and parameters to POST to S3
        contentType: "application/json"
        schema: ${file(doc/models/uploadResponse.json)}
      - name: ErrorResponse
        description: Error response
        contentType: "application/json"
        schema: ${file(doc/models/error.json)}
  exportGitVariables: false
