service: data-uploader

provider:
  name: aws
  runtime: python3.7
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  environment:
      API_URL:
          Fn::Join:
              - ""
              - - "https://"
                - Ref: "ApiGatewayRestApi"
                - ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"
  iamManagedPolicies:
      - arn:aws:iam::***REMOVED***:policy/ok-origo-dataplatform-data-upload-s3-put-object-${self:provider.stage}

package:
    include:
        - README.md
        - requirements.txt
        - generate_signed_post.py
        - frontend.py
    exclude:
        - env/**
        - requirements.in

functions:
  generate_signed_post:
    handler: generate_signed_post.handler
    environment:
        BUCKET: "ok-origo-dataplatform-data-upload-${self:provider.stage}"
    events:
      - http:
          path: /
          method: post
          authorizer:
            arn: arn:aws:lambda:${self:provider.region}:***REMOVED***:function:keycloak-authorizer-${self:provider.stage}-authenticate
            resultTtlInSeconds: 300
            identitySource: method.request.header.Authorization
            identityValidationExpression: "^Bearer [-0-9a-zA-Z\\._]*$"
            type: token

  frontend:
    handler: frontend.handler
    events:
      - http:
          path: /
          method: GET
